//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllPage
    {
        public int id { get; set; }
        public string linkUrl { get; set; }
        public string mycontent { get; set; }
    }
}
